### ISSUE TITLE
Suppress private/undocumented inherited classes from class signature in `python-apigen`

### ISSUE THREAD

**Issue by mhostetter** [jbms/sphinx-immaterial#130]
I noticed in `python-apigen` all base classes are added to a class signature, even private undocumented ones. For me, I get some weird signatures. In the screenshot below all I want to convey to the user is `class galois.Array(numpy.ndarray)` (all the other classes are undocumented).

![image](https://user-images.githubusercontent.com/12112573/178812955-7c4d57b9-6132-4ce4-a865-2fa55b19f59a.png)

My suggestion would be to either suppress classes that can't be reached / aren't document or all classes that start with `_` indicating they're private.

### Example

I made a `foo` project for testing. [foo-example.zip](https://github.com/jbms/sphinx-immaterial/files/9113106/foo-example.zip)

```python
# foo/__init__.py
from ._bar import A, B, C
```

```python
# foo/_bar.py
class A:
    """Class A docstring"""
    pass

class B:
    """Class B docstring"""
    pass

class Undocumented:
    """Class Undocumented docstring"""
    pass

class _Private:
    """Class _Private docstring"""
    pass

class C(A, B, Undocumented, _Private):
    """Class C docstring"""
    pass
```

![image](https://user-images.githubusercontent.com/12112573/179017702-f98e34d3-4e8f-4029-b30d-11992ea4b0d4.png)

My desired output would be `class foo.C(foo.A, foo.B)`.

**Comment by jbms** [comment]
I thought about doing some sort of filtering based on which classes are documented, but decided that it wouldn't work that well since you may want to list a base class from another project or from the standard library.

Instead you can use `autodoc-process-bases` to filter the list of bases shown:

https://jbms.github.io/sphinx-immaterial/apidoc/python/apigen.html#confval-python_apigen_show_base_classes
