### ISSUE TITLE
Fields render differently between RTD and GH Pages

### ISSUE THREAD

**Issue by mhostetter** [jbms/sphinx-immaterial#156]
Just an observation... I'm not sure which is preferable. Just mentioning because I'm surprised *they can* be different at all. I noticed this after building my docs with GitHub Pages. And then I noticed that this theme's docs display the same way.

### GitHub Pages

https://jbms.github.io/sphinx-immaterial/python_apigen_generated/bar.html

![image](https://user-images.githubusercontent.com/12112573/187531024-3ebc7bf4-71d4-46ec-aae6-e76e71f5345e.png)

### Read the Docs

https://sphinx-immaterial.readthedocs.io/en/latest/python_apigen_generated/bar.html

![image](https://user-images.githubusercontent.com/12112573/187531059-d2f398f5-89fe-4b32-a7b9-e016e154430d.png)

**Comment by jbms** [comment]
This appears to be due to a difference in the docutils version in use.

The addition of the colon was due to:

https://repo.or.cz/docutils.git/commit/dccf9c42d03e8e4a7c285c29fcce4ae90d7a0b6c

I'm not sure whether the colon is desirable or not, but if it is present, it should occur before the headerlink (which this theme adds via monkey patch).
