### ISSUE TITLE
Rendering of :kbd: role is a bit off

### ISSUE THREAD

**Issue by ruslo** [jbms/sphinx-immaterial#322]
Here is how `:kbd:` rendered in a light theme:

![Screenshot from 2024-02-07 16-51-13](https://github.com/jbms/sphinx-immaterial/assets/4346993/d0d3dc7b-58d0-497b-8443-c62fc4e54ab7)

It seems that the top of the object is missing.

It's slightly better with a dark theme:

![Screenshot from 2024-02-07 16-51-23](https://github.com/jbms/sphinx-immaterial/assets/4346993/977bf622-eb9f-42bd-a7de-374b8958dc7e)

Same code for the read-the-docs theme:

![Screenshot from 2024-02-07 16-58-56](https://github.com/jbms/sphinx-immaterial/assets/4346993/c4a450a3-e0d0-4fc5-bc7a-27eccf03fa21)

Live samples:
- https://read-the-docs-template-cdkwuttv.readthedocs.io/en/v1.0.0/highlight_text.html
- https://read-the-docs-template-cdkwuttv.readthedocs.io/en/v0.0.1/highlight_text.html

**Comment by 2bndy5** [comment]
Can you supply the RST code to reproduce?

It looks like the undesired offset happens when there's nested `<kbd>` elements.

```html
<kbd>
  <kbd>Ctrl<\kbd>
  +
  <kbd>F<\kbd>
<\kbd>
```

Have you also looked into the [`keys` role](https://jbms.github.io/sphinx-immaterial/keys.html#keys-extension-role)? The keys role's CSS is exclusive to this theme because the CSS is inherited from mkdocs-material theme...

**Comment by 2bndy5** [comment]
CSS for the keys role is inherited from mkdocs-material source: [src/assets/stylesheets/main/extensions/pymdownx/_keys.scss](https://github.com/jbms/sphinx-immaterial/blob/main/src/assets/stylesheets/main/extensions/pymdownx/_keys.scss).

But we also don't use any CSS from sphinx basic theme: [sphinx/themes/basic/static/basic.css_t](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/themes/basic/static/basic.css_t). But I don't see any CSS rules specific to kbd elements there.

Lastly, the RTD sphinx theme adds its own CSS specific to kbd elements: See [their _theme.sass file](https://github.com/readthedocs/sphinx_rtd_theme/blob/28c377f99a0fb8a6a7545ceaa599b7afd082d344/src/sass/_theme_rst.sass#L599-L608).

So, to solve this we would need to add some CSS for kbd elements that are generated by the `:kbd:` role and be careful to not alter the rules defined for the `:keys:` role.

## Just my opinion

I have some reservations about making any CSS changes because this theme is meant to be a port of the mkdocs-material theme to sphinx, not a material-design adaptation of the RTD sphinx theme... Looking at [how the kbd elements are styled in upstream mkdocs-material](https://squidfunk.github.io/mkdocs-material/reference/formatting/#adding-keyboard-keys), I feel like the current style is expected behavior.

There's also nothing stopping users from adding their own CSS to a project via sphinx, but having the different `:keys:` and `:kbd:` roles may complicate that idea too much for some doc authors.

**Comment by 2bndy5** [comment]
There also seems to be slight differences in how different browsers render the kbd elements. In Firefox, the offset looks fine, but Chrome seems to position the kbd elements' contents a bit higher than Firefox.

**Comment by ruslo** [comment]
> I have some reservations about making any CSS changes because this theme is meant to be a port of the mkdocs-material theme to sphinx, not a material-design adaptation of the RTD sphinx theme... Looking at [how the kbd elements are styled in upstream mkdocs-material](https://squidfunk.github.io/mkdocs-material/reference/formatting/#adding-keyboard-keys), I feel like the current style is expected behavior

Okay, I see, indeed the issue is the same there.

> In Firefox, the offset looks fine, but Chrome seems to position the kbd elements' contents a bit higher than Firefox

For me, Firefox looks similar:

![Screenshot from 2024-02-08 18-40-26](https://github.com/jbms/sphinx-immaterial/assets/4346993/97afbd5a-375f-4863-bab8-fc9016a4faae)

**Comment by 2bndy5** [comment]
I think the upstream artistic style can still be preserved while adding the requested visual distinction by simply darkening the kbd elements' `background-color` for light mode only:
```css
[data-md-color-scheme="default"] kbd {
  background-color: #dfdfdf;
}
```

which results in 
![image](https://github.com/jbms/sphinx-immaterial/assets/14963867/14d2794d-55a2-48bc-8c46-fbe5323dd1ef)

The `background-color` for kbd elements and the main body element is practically the same color in light mode.

**Comment by ruslo** [comment]
> I think the upstream artistic style can still be preserved while adding the requested visual distinction by simply darkening the kbd elements' background-color for light mode only

Look good:
- https://read-the-docs-template-cdkwuttv.readthedocs.io/en/v1.0.2/highlight_text.html

Code: https://github.com/ruslo/read_the_docs_template/commit/6951d7abccb1e2f9de88b584fd5ff53c568b797e

Thank you!
