### ISSUE TITLE
version selector not working

### ISSUE THREAD

**Issue by rayaldeng** [jbms/sphinx-immaterial#53]
Thank you for your efforts on this beautiful theme.

I've met some trouble utilizing the "version selector" function:

1. when using the "version info" approach, the dropdown menu would always show the top choice(not current version):
<img width="613" alt="截屏2022-03-28 下午5 53 55" src="https://user-images.githubusercontent.com/33215428/160374431-453473f9-6181-4ad0-9115-b408b7aadb31.png">
<img width="599" alt="截屏2022-03-28 下午5 54 09" src="https://user-images.githubusercontent.com/33215428/160374440-6da0a537-72f4-4834-b0f4-195815631f8a.png">
<img width="287" alt="截屏2022-03-28 下午5 59 28" src="https://user-images.githubusercontent.com/33215428/160374654-335ef0bd-4028-4f3d-af00-6361ca8c8835.png">

2. the `aliases` won't work(return 404 on static site with nginx)

3. I've also tried the "version_json" approach, which has not effect at all. Tried to put the JSON file on over the place yet won't wokring:
    - same directory with `conf.py`
    - parent directory of `conf.py`
    - also as mention in [docs](https://jbms.github.io/sphinx-immaterial/customization.html#confval-version_json):
        ```
        /versions.json
        /1.0/index.html
       /2.0/index.html
        ```
     - and all of above places together. 

Can anyone please help me with how to achieve this function?

----
environment:
```
sphinx==4.4.0
sphinx-immaterial==0.3.1
```

**Comment by 2bndy5** [comment]
Fwiw, I think the version selector is only q designed to work from a webserver. I'm not sure if you tried that. Hosting  different versions locally didn't work for me last time I tried it.

**Comment by jbms** [comment]
There is a bug in the detection of the current version that is fixed by #54.

Two things to clarify, though:
- `aliases` only affects the logic for detecting the current version, it does not affect which paths can be retrieved from your web server.  If you want a given path to behave as an alias, you are responsible for setting things up (e.g. with a rewrite rule on your webserver or a symlink) so that it works.
- If you use the `version_json` approach, you are responsible for ensuring the versions.json file can be retrieved from the expected path.  When you build your documentation using this theme, there is nothing that actually looks for a versions.json file and copies it to some location.

**Comment by jbms** [comment]
What @2bndy5 said as far as a web server is also true --- the way the theme currently retrieves the versions.json file is incompatible with `file://`.  We could make it work, by converting it to a javascript file and loading it via a script tag, as is done for the search index, but I'm not sure there is a really a need for it to work with `file://`.

**Comment by 2bndy5** [comment]
@jbms You make it sound simple... Only reason I can think of is being able to be sure my commit will work same from the server and `file://`. Making something that I cannot locally check/run properly can often result in messy git history. Is that a fix that might be useful upstream? Or is it exclusive to this theme?

**Comment by jbms** [comment]
The versioning in mkdocs-material is intended to be used with the `mike` package, so I don't think the changes I describe would be desired there, since it would require a different format for the version file.

Note that you can easily run a local web server --- e.g. `npm install http-server` and then run `http-server` to serve a local directory.

**Comment by 2bndy5** [comment]
Python3 std libs should have a similar command, I think. 
```
python -m http.server
```
I found a plugin in VSCode that puts it into a button.

**Comment by rayaldeng** [comment]
sorry for this delayed response cuz I was stuck in quarantine.

1. First of all, allow me to say thank you both for your quick response and helpful advises. 
The  #54 perfectly fix my problem, now version dropdown works as expected.

2. Fully understand how `alias` work now and hence the required folder structure by `versions.json`, I put a jump.js to ensure all alias works fine.
```bash
/alias.html--> jump.js
/versions.json
/1.0/index.html
/2.0/index.html
```
-------------------------------------------------------
Still got a maybe unnecessary worry about how `base_url` compatible with `version dropdown`:
- let's say I got 2 version : `https://myserver/1.1/` and `https://myserver/1.2/`, do I have to make sure the `base_url` in `conf.py` in each version to be `https://myserver/${version_num}/`, or I can leave it as `https://myserver/` and it  does not bother?
