### ISSUE TITLE
add option to disable cross-linking C++ parameters

### ISSUE THREAD

**Issue by 2bndy5** [jbms/sphinx-immaterial#70]
There are 2 reasons why I think this would be useful.
1. If a documented API uses a lot of parameters, then the ToC gets very long and visually complex (despite the `include_object_description_fields_in_toc` config value).
2. When writing new documentation for API, it can be annoying to see a warning related to missing parameter descriptions.
   - I wouldn't do this myself, but some might consider a parameter's name/type as "self-descriptive enough." Thus, they would deliberately neglect adding parameter description(s).

The only objection I can think of is: If disabling cross-linked parameters, **would it affect other C++ domain customization** options, namely synopses?

I imagine that the option's name would be `cpp_cross_link_parameters` (defaults to True). This way it can be used independently from similar implementations for other domains (like Java or JS) - thinking optimistically about future additions 😃 .

**Comment by jbms** [comment]
Possibly the option should only control whether they are included in the TOC, rather than whether they are cross-linked.  I agree that if you have many entities defined on the same page, including the parameters in the TOC may not be desired.

To be clear, there is no warning if you leave a parameter undocumented.  However, there is a warning "invalid parameter name" if you add a `:param xxx:` field for a parameter that is not defined by any of the listed signatures.  That helps prevent misspelled parameter names.

We could have an option to disable cross-linking of parameters entirely, which would presumably eliminate any such warnings and would eliminate parameter synopses (and then references to parameters would just link to the signature itself as is the default behavior from Sphinx).  However I'm not sure how useful that option would be.  (Synopses of other C++ entities would still be supported.)

**Comment by 2bndy5** [comment]
>there is a warning "invalid parameter name" if you add a `:param xxx:` field for a parameter that is not defined by any of the listed signatures. That helps prevent misspelled parameter names.

That kinda clears up some confusion I have with #67

**Comment by 2bndy5** [comment]
>Possibly the option should only control whether they are included in the TOC, rather than whether they are cross-linked.

So, the option name would be more like `cpp_parameters_in_toc`? That seems to match the other C++ specific options. I'm tryting to avoid confusion with the `include_object_description_fields_in_toc` option.

**Comment by jbms** [comment]
Yeah I think `cpp_parameters_in_toc` is a good name.
